### ISSUE TITLE
Hacktoberfest 2023

### ISSUE THREAD

**Issue by serhatbek** [Jan-Fcloud/hacktoberfest-2023-participants#21]
# Hacktoberfest 2023 EXCLUDED 
After I did my pull reguest, I checked the Hacktoberfest 2023 page and it says 'This repository is EXCLUDED from Hacktoberfest, and it will not count for  towards your participation'. :(

**Comment by Jan-Fcloud** [comment]
Hi, yes this can occur as mentioned both in the README and the main site of the page:
- https://github.com/Jan-Fcloud/hacktoberfest-2023-participants?tab=readme-ov-file#disclaimer-for-pull-requests

Things such as only adding your profile or slight color changes in a css file or anything like it, most likely will not count and require a bigger contribution.
