### ISSUE TITLE
A Hacktoberfest themed 404 page

### ISSUE THREAD

**Issue by Jan-Fcloud** [Jan-Fcloud/hacktoberfest-2023-participants#7]
Another thing we could add, is a 404 page in the style of the main Hacktoberfest website.

Maybe with a text saying _"Uh oh, you hacked too far..."_ and a big button underneath to go back to the main page of this repo.

**Comment by Virtual4087** [comment]
Where should we add the 404?

**Comment by SurajPrakash24** [comment]
Can You please assign it to me. I would like to contribute to this page

**Comment by Jan-Fcloud** [comment]
Issue implemented by @NsCracker 

Thank you for taking part and good luck on further projects!
